### PR TITLE
This code will track shape and color using opencv, no ROS yet

### PR DESCRIPTION
**Pull request by BatataKingdom**

### CODE REVIEW

**Comment by chicagoedt** [comment]
Can one of the admins ok this patch for build on Jenkins?

**Comment by l0g1x** [comment]
ok to test

**Comment by l0g1x** [comment]
add to whitelist

**Comment by chicagoedt** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.chicagoedt.org/job/Software_IGVC_Upstream/51/
Test Passed.

**Comment by l0g1x** [comment]
@BatataKingdom Can you create this into a seperate 'flag_detection' package?

go into the main src folder (where you see all the packages) and type this
`catkin_create_pkg flag_detection rospy libopencv-dev dynamic_reconfigure std_msgs`

@basheersubei can you double check he has all the required dependencies? i look up for opencv and its either libopencv-dev or python-opencv

**Comment by bsubei** [comment]
I'm not sure the dependencies matter. rospy is weird and seems to work regardless of your CMakeLists or package.xml dependencies.

**Pull request merged**
