### PR TITLE
organizes and cleans new line_detection package and adds nmea_navsat_driver submodule

### PR DESCRIPTION
**Pull request by bsubei**
all misc files have been moved out of source.
dynamic_reconfigure has been added.
a generic line_detection node has been created (so that people can just gut it or modify it to change the algorithm).
I even linted the new nodes so that they're PEP8 conforming

### CODE REVIEW

**Comment by bsubei** [comment]
wait i'm gonna add more commits to this...

**Comment by bsubei** [comment]
still needs basic tests, dont merge yet

**Comment by l0g1x** [comment]
test this please

**Comment by l0g1x** [comment]
retest this please

**Pull request merged**
