### PR TITLE
Clean up, package fixes, etc. 

### PR DESCRIPTION
**Pull request by l0g1x**
Added a lot of the  packages i had on my local machine.

### CODE REVIEW

**Comment by bsubei** [comment]
there's so many changes that I can't even view them!

**Comment by bsubei** [comment]
just realized 3a1b7f2736a2475fcf1d43f5448f042caa570c29 has a ton of binary files (gazebo_config/build) folders... We don't want those, do we? They're probably huge files...

**Comment by l0g1x** [comment]
Yeah taking care of that now. Warren saw that too

**Comment by bsubei** [comment]
@l0g1x make sure you strip those commits (remove them entirely). Don't just create a new commit that deletes the binaries. That would still leave the binaries being part of history (which is what bloats the size of the repo).

^ make sure you backup everything before you start stripping commits and deleting them.

**Comment by l0g1x** [comment]
Can someone take a look at this again? Pretty sure i fixed everything. There should be no simulation stuff in the development branch. Likewise, there should be no development specific things (roboteq_node, sicktim_3xx, hardware sensors etc) inside simulation branch

**Comment by bsubei** [comment]
that's way too many changes in one commit. If any changes are redundant (adding files in one commit then removing them in the next), then you should strip commits instead of adding new ones.

**Pull request merged**
