### PR TITLE
Roy test for pull request

### PR DESCRIPTION
**Pull request by roymoran**
test pull request

### CODE REVIEW

**Comment by l0g1x** [comment]
Can one of the admins verify this patch?

**Comment by wfriedl** [comment]
test this please

**Comment by l0g1x** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.chicagoedt.org/job/Software_IGVC_Upstream/38/
Test PASSed.

**Comment by l0g1x** [comment]
test this please

**Comment by wfriedl** [comment]
test this please

**Comment by l0g1x** [comment]
Test Passed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.chicagoedt.org/job/Software_IGVC_Upstream/39/
Test Passed.

**Comment by l0g1x** [comment]
test this please

**Comment by l0g1x** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.chicagoedt.org/job/Software_IGVC_Upstream/40/
Test PASSed.

**Pull request closed without merging**
